supported_langs_html = 'https://dl.fbaipublicfiles.com/mms/misc/language_coverage_mms.html'
supported_langs_out_cols = ['ISO 693-3', 'Language Name']
api_url_track = 'http://fluids.ai:1337/live-storms/'
api_url_forecast = 'http://fluids.ai:1337/forecasts/'
max_storm_history = 10
default_system = "You are an AI assistant that helps people find information."
redis_host = 'huraim.redis.cache.windows.net'
redis_port = '6380'
redis_latest_audio_key = 'latest_audio_metadata'